spring:
  config:
    import:
      - classpath:config/application-secret.yml
jwt:
  access:
    secret: ${jwt.access.secret}
    expiration: ${jwt.access.expiration}
  refresh:
    secret: ${jwt.refresh.secret}
    expiration: ${jwt.refresh.expiration}