spring:
  profiles:
    include:
      - datasource
    active: datasource, twilio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  config:
    import: classpath:config/application-twilio.yml

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.beans.factory.support: DEBUG
    org.springframework.context.annotation: DEBUG