spring:
  profiles:
    include:
      - datasource
    active: datasource, twilio, secrets
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
  config:
    import:
      - classpath:/application-datasource.yml
      - classpath:/application-secrets.yml
      - classpath:config/application-twilio.yml

logging:
  file:
    name: /var/log/energytajo/app.log
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
    org.springframework.beans.factory.support: DEBUG
    org.springframework.context.annotation: DEBUG

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: FNYrNLeeGce28CcuoIlrdYrCNZgRg3MAMgbfkVDhmj4=
