name: Deploy via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
        shell: bash

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: /tmp/ssh_key
          port: 22
          source: "./resources/config/main/application.yml"
          target: "/home/ubuntu/energytajo/config/"