name: EnergyTajo CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: get code from remote repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          submodules: true

      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy build file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/libs/*.jar"
          target: "~source/build/libs"
          rm: true

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "#### Enter the test-was section ####"

            SOURCE_DIR=source/build/libs
            FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
            PID=`ps -ef | grep 'java -jar' | grep -v "grep" | awk '{print $2}'`
            LOG_FILE=source/build/logfile_$(date +"%Y%m%d_%H%M%S").log
            if [ -z "$PID" ]; then
                echo "#### THERE IS NO PROCESS ####"
            else
                echo "#### KILL $PID ####"
                kill $PID
            fi

            echo "#### CREATE symbolic link ~/EnergyTajo.jar ####"
            ln -sf $SOURCE_DIR/$FILE_NAME ~/EnergyTajo.jar

            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"
            java -jar $SOURCE_DIR/$FILE_NAME > $LOG_FILE 2>&1 &

      - name: Verify HTTPS Deployment
        run: |
          echo "#### Checking HTTPS response ####"
          sleep 10  # Wait for the server to start
          curl -I https://your-domain.com || echo "#### HTTPS check failed ####"
