name: EnergyTajo CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: get code from remote repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          submodules: true

      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload using rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: build/libs/
          remote_path: ~/source/build/libs/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "#### Enter the deployment section ####"

            FILE_NAME=$(find ~/source/build/libs -maxdepth 1 -name "*.jar" | head -n 1)
            PID=$(ps -ef | grep 'java -jar' | grep -v "grep" | awk '{print $2}')
            LOG_DIR=~/source/build
            LOG_FILE=$LOG_DIR/logfile_$(date +"%Y%m%d_%H%M%S").log

            mkdir -p $LOG_DIR

            if [ -z "$PID" ]; then
              echo "#### NO RUNNING PROCESS ####"
            else
              echo "#### KILLING PROCESS $PID ####"
              kill $PID
            fi

            echo "#### LINKING $FILE_NAME to ~/EnergyTajo.jar ####"
            ln -sf $FILE_NAME ~/EnergyTajo.jar

            echo "#### RUNNING JAR ####"
            nohup java -jar ~/EnergyTajo.jar > $LOG_FILE 2>&1 &

      - name: Verify HTTPS Deployment
        run: |
          echo "#### Checking HTTPS response ####"
          sleep 10
          curl -I https://energytajo.site || echo "#### HTTPS check failed ####"